In [2]:
import numpy as np
import pandas as pd

In [18]:
weather_dataset = pd.read_csv('weather_wwo_manila_2015.csv', skipinitialspace=True, encoding='cp1252')
weather_dataset = weather_dataset[['dt', 'precipMM']]
weather_dataset = weather_dataset.set_index(['dt'])
weather_dataset

                  precipMM
dt
1/1/2015 0:00     0.000000
1/1/2015 0:15     0.000000
1/1/2015 0:30     0.000000
1/1/2015 0:45     0.000000
1/1/2015 1:00     0.000000
1/1/2015 1:15     0.000000
1/1/2015 1:30     0.000000
1/1/2015 1:45     0.000000
1/1/2015 2:00     0.000000
1/1/2015 2:15     0.000000
1/1/2015 2:30     0.000000
1/1/2015 2:45     0.000000
1/1/2015 3:00     0.000000
1/1/2015 3:15     0.000000
1/1/2015 3:30     0.000000
1/1/2015 3:45     0.000000
1/1/2015 4:00     0.000000
1/1/2015 4:15     0.000000
1/1/2015 4:30     0.000000
1/1/2015 4:45     0.000000
1/1/2015 5:00     0.000000
1/1/2015 5:15     0.000000
1/1/2015 5:30     0.000000
1/1/2015 5:45     0.000000
1/1/2015 6:00     0.000000
1/1/2015 6:15     0.001106
1/1/2015 6:30     0.002212
1/1/2015 6:45     0.003319
1/1/2015 7:00     0.004425
1/1/2015 7:15     0.005531
...                    ...
12/31/2015 16:30  0.267699
12/31/2015 16:45  0.133850
12/31/2015 17:00  0.000000
12/31/2015 17:15  0.000000
12/31/2015 17:30  0.000000
12/31/2015 17:45  0.000000
12/31/2015 18:00  0.000000
12/31/2015 18:15  0.000000
12/31/2015 18:30  0.000000
12/31/2015 18:45  0.000000
12/31/2015 19:00  0.000000
12/31/2015 19:15  0.000000
12/31/2015 19:30  0.000000
12/31/2015 19:45  0.000000
12/31/2015 20:00  0.000000
12/31/2015 20:15  0.000000
12/31/2015 20:30  0.000000
12/31/2015 20:45  0.000000
12/31/2015 21:00  0.000000
12/31/2015 21:15  0.001106
12/31/2015 21:30  0.002212
12/31/2015 21:45  0.003319
12/31/2015 22:00  0.004425
12/31/2015 22:15  0.005531
12/31/2015 22:30  0.006637
12/31/2015 22:45  0.007743
12/31/2015 23:00  0.008850
12/31/2015 23:15  0.022616
12/31/2015 23:30  0.036382
12/31/2015 23:45  0.050147

[35040 rows x 1 columns]

In [20]:
# Duplicate dataset
result_df = weather_dataset.copy()

# Converting the index as date
result_df.index = pd.to_datetime(result_df.index)

# Create column work_day
result_df['work_day'] = ((result_df.index.dayofweek) < 5).astype(int)

# Consider non-working holiday
result_df.loc['2015-01-01', 'work_day'] = 0
result_df.loc['2015-01-02', 'work_day'] = 0
result_df.loc['2015-01-15', 'work_day'] = 0
result_df.loc['2015-01-16', 'work_day'] = 0
result_df.loc['2015-01-19', 'work_day'] = 0
result_df.loc['2015-02-19', 'work_day'] = 0
result_df.loc['2015-02-25', 'work_day'] = 0
result_df.loc['2015-03-16', 'work_day'] = 0
result_df.loc['2015-04-02', 'work_day'] = 0
result_df.loc['2015-04-03', 'work_day'] = 0
result_df.loc['2015-04-04', 'work_day'] = 0
result_df.loc['2015-04-09', 'work_day'] = 0
result_df.loc['2015-05-01', 'work_day'] = 0
result_df.loc['2015-06-11', 'work_day'] = 0
result_df.loc['2015-06-12', 'work_day'] = 0
result_df.loc['2015-06-24', 'work_day'] = 0
result_df.loc['2015-07-17', 'work_day'] = 0
result_df.loc['2015-08-21', 'work_day'] = 0
result_df.loc['2015-08-31', 'work_day'] = 0
result_df.loc['2015-09-25', 'work_day'] = 0
result_df.loc['2015-11-01', 'work_day'] = 0
result_df.loc['2015-11-17', 'work_day'] = 0
result_df.loc['2015-11-18', 'work_day'] = 0
result_df.loc['2015-11-19', 'work_day'] = 0
result_df.loc['2015-11-20', 'work_day'] = 0
result_df.loc['2015-11-30', 'work_day'] = 0
result_df.loc['2015-12-24', 'work_day'] = 0
result_df.loc['2015-12-25', 'work_day'] = 0
result_df.loc['2015-12-30', 'work_day'] = 0
result_df.loc['2015-12-31', 'work_day'] = 0

# # Consider class suspension
result_df.loc['2015-01-09', 'work_day'] = 0
result_df.loc['2015-01-14', 'work_day'] = 0
result_df.loc['2015-03-17', 'work_day'] = 0
result_df.loc['2015-07-06', 'work_day'] = 0
result_df.loc['2015-07-07', 'work_day'] = 0
result_df.loc['2015-07-08', 'work_day'] = 0
result_df.loc['2015-07-09', 'work_day'] = 0
result_df.loc['2015-07-10', 'work_day'] = 0
result_df.loc['2015-07-27', 'work_day'] = 0
result_df.loc['2015-07-28', 'work_day'] = 0
result_df.loc['2015-07-29', 'work_day'] = 0
result_df.loc['2015-10-02', 'work_day'] = 0
result_df.loc['2015-10-13', 'work_day'] = 0
result_df.loc['2015-10-19', 'work_day'] = 0
result_df.loc['2015-10-20', 'work_day'] = 0
result_df.loc['2015-10-30', 'work_day'] = 0
result_df.loc['2015-10-31', 'work_day'] = 0
result_df.loc['2015-11-02', 'work_day'] = 0
result_df.loc['2015-11-03', 'work_day'] = 0
result_df.loc['2015-12-04', 'work_day'] = 0
result_df.loc['2015-12-14', 'work_day'] = 0
result_df.loc['2015-12-15', 'work_day'] = 0
result_df.loc['2015-12-16', 'work_day'] = 0


# result_df['peak_hour'] = 0

# # Set morning peak hour

# start = datetime.time(7,0,0)
# end = datetime.time(10,0,0)

# result_df.loc[result_df.between_time(start, end).index, 'peak_hour'] = 1

# # Set afternoon peak hour

# start = datetime.time(16,0,0)
# end = datetime.time(19,0,0)

# result_df.loc[result_df.between_time(start, end).index, 'peak_hour'] = 1

# # Parameters
# IS_WORKDAY = 0
# IS_PEAKHOUR = 1

# # Filter based on parameters
# work_day_peak_hour_df = result_df[(result_df['work_day'] == IS_WORKDAY) & (result_df['peak_hour'] == IS_PEAKHOUR)]

# # Remove work_day and peak_hour columns
# work_day_peak_hour_df.drop(['work_day', 'peak_hour'], axis=1, inplace=True)

KeyError: "['2015-01-01' '2015-01-02' '2015-01-02' '2015-01-02'] not in index"